#!/usr/bin/env python

print "Content-type:text/html\r\n\r\n"

print """<html>

<form action="speakUp.py" method="get">
Message: <input type="text" name="msg">
<input type="submit" value="Speak!" />
</form>

</html>
"""
